version: '3.8'

services:
  telegram-bot:
    build: .
    pull_policy: build  # 添加这一行，跳过在线拉取
    container_name: hkbu-telegram-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"